import {useEffect,useState} from 'react';
export function initializeAppearance(){
 const media=window.matchMedia('(prefers-color-scheme: dark)');
 const apply=()=>{let saved='';try{saved=localStorage.getItem('woe-theme')||''}catch{}document.documentElement.dataset.theme=saved==='light'||saved==='dark'?saved:media.matches?'dark':'light'};
 apply();media.addEventListener('change',apply);window.addEventListener('storage',apply);
}
export function ThemeToggle(){
 const [dark,setDark]=useState(()=>document.documentElement.dataset.theme==='dark');
 useEffect(()=>{const sync=()=>setDark(document.documentElement.dataset.theme==='dark');window.addEventListener('storage',sync);const media=window.matchMedia('(prefers-color-scheme: dark)');media.addEventListener('change',sync);return()=>{window.removeEventListener('storage',sync);media.removeEventListener('change',sync)}},[]);
 return <button className="theme-toggle" type="button" aria-label={dark?'Switch to light mode':'Switch to dark mode'} aria-pressed={dark} onClick={()=>{const next=dark?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('woe-theme',next)}catch{}setDark(!dark)}}><span aria-hidden="true">{dark?'☀':'☾'}</span>{dark?'Light mode':'Dark mode'}</button>;
}
export type MapPalette='standard'|'accessible';
export function useMapPalette(){const [palette,setPalette]=useState<MapPalette>(()=>{try{return localStorage.getItem('woe-map-palette')==='accessible'?'accessible':'standard'}catch{return 'standard'}});useEffect(()=>{const sync=()=>{try{setPalette(localStorage.getItem('woe-map-palette')==='accessible'?'accessible':'standard')}catch{}};window.addEventListener('map-palette-changed',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('map-palette-changed',sync);window.removeEventListener('storage',sync)}},[]);return [palette,(value:MapPalette)=>{setPalette(value);try{localStorage.setItem('woe-map-palette',value)}catch{}window.dispatchEvent(new Event('map-palette-changed'))}] as const;}
export function MapPaletteControl({value,onChange}:{value:MapPalette;onChange:(value:MapPalette)=>void}){return <label className="map-palette-control">Map colours<select value={value} onChange={e=>onChange(e.target.value as MapPalette)}><option value="standard">Original colours</option><option value="accessible">Colourblind-friendly</option></select></label>}
const colours=['#0072b2','#e69f00','#009e73','#cc79a7','#56b4e9','#d55e00','#7d6da8','#454545'];
export const accessibleColour=(index:number)=>colours[((index%colours.length)+colours.length)%colours.length];
export function senateColour(party:string,rating:string,original:string,palette:MapPalette){if(palette==='standard')return original;if(rating==='tossup')return '#d8d8d8';const colours:Record<string,string[]>={D:['#005b8c','#368db9','#91c5df'],R:['#9c4c00','#d58c25','#efd3a0'],I:['#70528c','#987eb2','#cbbcdc']};return (colours[party]||colours.I)[rating==='safe'?0:rating==='likely'?1:2];}
export const palettePattern=(index:number)=>Math.floor(index/8)%4;
export function MapPatternDefs({prefix,count}:{prefix:string;count:number}){return <defs>{Array.from({length:count},(_,index)=><pattern key={index} id={`${prefix}-${index}`} width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill={accessibleColour(index)}/>{palettePattern(index)===1&&<path d="M-2 2 2-2M0 8 8 0M6 10 10 6" stroke="white" strokeOpacity=".6" strokeWidth="1.5"/>}{palettePattern(index)===2&&<circle cx="4" cy="4" r="1.5" fill="white" fillOpacity=".65"/>}{palettePattern(index)===3&&<path d="M4 0V8" stroke="white" strokeOpacity=".6" strokeWidth="2"/>}</pattern>)}</defs>}
export function MapSwatch({index,original,palette,patterns=true}:{index:number;original:string;palette:MapPalette;patterns?:boolean}){const pattern=palettePattern(index);const backgroundImage=patterns&&palette==='accessible'&&pattern===1?'repeating-linear-gradient(135deg,transparent 0 4px,#ffffff99 4px 5.5px)':patterns&&palette==='accessible'&&pattern===2?'radial-gradient(#ffffffaa 1.5px,transparent 1.5px)':patterns&&palette==='accessible'&&pattern===3?'repeating-linear-gradient(90deg,transparent 0 3px,#ffffff99 3px 5px)':undefined;return <i className="map-colour-swatch" style={{backgroundColor:palette==='accessible'?accessibleColour(index):original,backgroundImage,backgroundSize:pattern===2?'8px 8px':undefined}}/>}
