import {useEffect,useState} from 'react';import {getIdeologyScores,getParliamentOrder} from '../db/politics';import {politicalAxes,orderByAxes,type Axis} from '../lib/political-axes';
import type {WorldElection} from '../lib/world';
import {hemicycleLayout,parliamentGroups} from '../lib/parliament';
export function Parliament({election:e,preview=false,heading,caption}:{election:WorldElection;preview?:boolean;heading?:string;caption?:string}){
  const [sort,setSort]=useState('table'),[axes,setAxes]=useState<Axis[]>([]),[reverse,setReverse]=useState(false),[order,setOrder]=useState<string[]>([]),[message,setMessage]=useState('');
  const activeAxes=sort==='all'?politicalAxes.map(a=>a[0]):sort==='custom'?axes:politicalAxes.some(a=>a[0]===sort)?[sort as Axis]:[];
  const axisKey=activeAxes.join(',');
  useEffect(()=>{let active=true;setOrder([]);setMessage('');if(!activeAxes.length)return;setMessage('Sorting parliament…');(async()=>{try{const ids=preview?orderByAxes(e.results,activeAxes,await getIdeologyScores(),reverse):await getParliamentOrder(e.id,activeAxes,reverse);if(active){setOrder(ids);setMessage('')}}catch{if(active)setMessage('Ideology ordering is unavailable. The recorded table order remains visible.')}})();return()=>{active=false}},[e.id,e.results,axisKey,reverse,preview]);
  const model=parliamentGroups(e);if(!model)return null;
  if(order.length){const rank=new Map(order.map((id,i)=>[id,i]));model.groups.sort((a,b)=>(rank.get(a.id)??Number.MAX_SAFE_INTEGER)-(rank.get(b.id)??Number.MAX_SAFE_INTEGER));}
  const {groups,entered,total,knownTotal,missing}=model;
  const dots=hemicycleLayout(total);let offset=0;
  const majority=e.majorityThreshold??(knownTotal?Math.floor(total/2)+1:null);
  const summary=groups.map(g=>`${g.name}: ${g.seats} seats`).join('; ');
  return <section className="parliament-panel"><div className="parliament-heading"><div><div className="kicker">{preview?'EDITOR PREVIEW':'PARLIAMENT COMPOSITION'}</div><h2>{heading??(preview?'Parliament preview':e.status==='scheduled'?'Upcoming parliament scenario':'The new parliament')}</h2></div>{majority!=null&&<span className="parliament-majority">{majority} seats for a majority</span>}</div><div className="parliament-sort"><label>Arrange parties<select value={sort} onChange={ev=>setSort(ev.target.value)}><option value="table">Recorded table order</option>{politicalAxes.map(([key,left,right])=><option key={key} value={key}>{left} ↔ {right}</option>)}<option value="all">All nine axes combined</option><option value="custom">Choose a combination</option></select></label>{sort!=='table'&&<label>Direction<select value={reverse?'reverse':'forward'} onChange={ev=>setReverse(ev.target.value==='reverse')}><option value="forward">First pole to second pole</option><option value="reverse">Second pole to first pole</option></select></label>}{sort==='custom'&&<fieldset><legend>Combine axes with equal weight</legend>{politicalAxes.map(([key,left,right])=><label key={key} className="checklabel"><input type="checkbox" checked={axes.includes(key)} onChange={ev=>setAxes(ev.target.checked?[...axes,key]:axes.filter(a=>a!==key))}/>{left} ↔ {right}</label>)}</fieldset>}</div>{message&&<p role="status">{message}</p>}<svg className="parliament-chart" viewBox="0 0 600 330" role="img" aria-label={`Parliament seat diagram. ${summary}`}><title>{summary}</title>{groups.map(g=>{const seats=dots.slice(offset,offset+g.seats);offset+=g.seats;return <g key={g.id} fill={g.color}><title>{g.name}: {g.seats} seats</title>{seats.map((d,i)=><circle key={i} cx={d.x} cy={d.y} r={d.radius}/>)}</g>;})}<text x="300" y="239" textAnchor="middle" className="parliament-total">{total.toLocaleString()}</text><text x="300" y="263" textAnchor="middle" className="parliament-total-label">{knownTotal?'CHAMBER SEATS':'SEATS ENTERED'}</text></svg><div className="parliament-legend">{groups.map(g=><div key={g.id}><i style={{background:g.color}}/><span>{g.name}</span><b>{g.seats.toLocaleString()}</b></div>)}</div><p className="meta">{caption??<>One dot per seat. {sort==='table'?'Parties follow the result-table order.':'Parties are arranged using our ideology classifications. Each selected axis has equal weight; linked ideologies are averaged within an axis. Unassessed parties follow assessed parties, and ties keep the recorded order. Numeric classifications remain private to our moderators.'} {knownTotal?`${entered.toLocaleString()} of ${total.toLocaleString()} seats entered.`:'Chamber total has not been entered.'}{missing?' Some parties have no seat count yet.':''} {e.status==='scheduled'?' Upcoming elections show entered seat scenarios, not election results.':e.resultStatus==='provisional'?'Results are provisional.':''}</>}</p></section>;
}
