export const legitimacyLevels=[['unassessed','Unassessed','#cbd5e1'],['credible','Credible / competitive','#27804c'],['concerns','Significant concerns','#d39b24'],['disputed','Seriously disputed','#cc6430'],['uncompetitive','Uncompetitive / restricted','#ae2638']] as const;
export type Legitimacy={level:typeof legitimacyLevels[number][0];summary:string;reviewed:string;sources:{label:string;url:string}[]};
export type Observer={id:string;organization:string;status:'invited'|'present'|'report-published'|'not-admitted';assessment:string;url:string;date:string};
export const emptyLegitimacy=():Legitimacy=>({level:'unassessed',summary:'',reviewed:'',sources:[]});
export function legitimacyInfo(value?:Legitimacy){return legitimacyLevels.find(l=>l[0]===value?.level)||legitimacyLevels[0];}
const date=(s:string)=>s===''||/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
export function safeSource(url:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
export function validateLegitimacy(l?:Legitimacy){if(l===undefined)return;if(!l||!legitimacyLevels.some(x=>x[0]===l.level)||typeof l.summary!=='string'||l.summary.length>10000||typeof l.reviewed!=='string'||!date(l.reviewed)||!Array.isArray(l.sources)||l.sources.length>30||l.sources.some(s=>!s||typeof s.label!=='string'||!s.label.trim()||s.label.length>300||typeof s.url!=='string'||s.url.length>2000||!safeSource(s.url)))throw Error('Check the legitimacy assessment, review date and sources.');if(l.level!=='unassessed'&&(!l.summary.trim()||!l.reviewed||!l.sources.length))throw Error('A legitimacy assessment needs an explanation, review date and source.');}
export function validateObservers(observers?:Observer[]){if(observers===undefined)return;if(!Array.isArray(observers)||observers.length>100||new Set(observers.map(o=>o.id)).size!==observers.length||observers.some(o=>!o||typeof o.id!=='string'||!o.id||typeof o.organization!=='string'||!o.organization.trim()||o.organization.length>300||!['invited','present','report-published','not-admitted'].includes(o.status)||typeof o.assessment!=='string'||o.assessment.length>10000||typeof o.date!=='string'||!date(o.date)||typeof o.url!=='string'||o.url.length>2000||(o.url!==''&&!safeSource(o.url))||(o.status==='report-published'&&(!o.url||!o.assessment.trim()))))throw Error('Check observer organizations, report links and dates. Published reports need a link and findings.');}
