export type Party='D'|'R'|'I';
export type Rating='safe'|'likely'|'lean'|'tossup';
export type Mode='polling'|'results';
export type Candidate={id:string;name:string;party:Party;poll:number;votes:number};
export type Race={id:string;state:string;code:string;special:boolean;incumbent:Party;incumbentName:string;independentCaucus:Party;polling:{party:Party;rating:Rating};results:{party:Party;rating:Rating;called:string;reporting:number};probabilities:Record<Mode,{manual:boolean;useNumbers:boolean;D:number;R:number;I:number}>;candidates:Candidate[];notes:string;source:string};
export type Senate={id:string;title:string;updated:string;baseline:{D:number;R:number;I:number;independentCaucus:Party};tieBreaker:Party;ratingChances:{safe:number;likely:number;lean:number};uncertainty:{polling:number;results:number};races:Race[]};
const names:Record<string,string>={AK:'Alaska',AL:'Alabama',AR:'Arkansas',CO:'Colorado',DE:'Delaware',FL:'Florida',GA:'Georgia',IA:'Iowa',ID:'Idaho',IL:'Illinois',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',MA:'Massachusetts',ME:'Maine',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MT:'Montana',NC:'North Carolina',NE:'Nebraska',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',VA:'Virginia',WV:'West Virginia',WY:'Wyoming'};
const dem=new Set('CO DE GA IL MA MI MN NH NJ NM OR RI VA'.split(' '));
export function defaultSenate():Senate{return {id:'senate-2026',title:'U.S. Senate elections 2026',updated:'',baseline:{D:32,R:31,I:2,independentCaucus:'D'},tieBreaker:'R',ratingChances:{safe:99,likely:85,lean:65},uncertainty:{polling:4,results:12},races:Object.entries(names).map(([code,state])=>({id:code,state,code,special:['FL','OH'].includes(code),incumbent:dem.has(code)?'D':'R',incumbentName:'',independentCaucus:'I',polling:{party:dem.has(code)?'D':'R',rating:'tossup'},results:{party:dem.has(code)?'D':'R',rating:'tossup',called:'',reporting:0},probabilities:{polling:{manual:false,useNumbers:true,D:50,R:50,I:0},results:{manual:false,useNumbers:true,D:50,R:50,I:0}},candidates:[{id:code+'-D',name:'',party:'D',poll:0,votes:0},{id:code+'-R',name:'',party:'R',poll:0,votes:0}],notes:'',source:''}))};}
export const partyName={D:'Democratic',R:'Republican',I:'Independent'};
export const shades={D:{safe:'#174a9c',likely:'#477dcc',lean:'#a6c6f1'},R:{safe:'#aa202a',likely:'#d95f65',lean:'#f1b3b6'},I:{safe:'#66338f',likely:'#9d70bc',lean:'#d5b8e7'}};
export function calledCandidate(r:Race){return r.candidates.find(c=>c.id===r.results.called)}
export function appearance(r:Race,mode:Mode){const called=mode==='results'?calledCandidate(r):undefined;const entry=r[mode];const party=called?.party||entry.party;const rating=called?'safe':entry.rating;return {party,rating,color:rating==='tossup'?'#e4d9b8':shades[party][rating],flip:rating!=='tossup'&&party!==r.incumbent,called:!!called};}
export function raceProbabilities(r:Race,mode:Mode,s:Senate):Record<Party,number>{const called=mode==='results'?calledCandidate(r):undefined;if(called)return {D:called.party==='D'?1:0,R:called.party==='R'?1:0,I:called.party==='I'?1:0};const p=r.probabilities[mode];if(p.manual)return {D:p.D/100,R:p.R/100,I:p.I/100};if(p.useNumbers){const values=r.candidates.map(c=>mode==='polling'?c.poll:c.votes);const total=values.reduce((n,v)=>n+v,0);if(total>0){const scores=mode==='polling'?values:values.map(v=>100*v/total);const scale=mode==='polling'?s.uncertainty.polling:Math.max(.5,s.uncertainty.results*Math.sqrt(1-r.results.reporting/100));const max=Math.max(...scores);const weights=scores.map(v=>Math.exp((v-max)/scale));const sum=weights.reduce((n,v)=>n+v,0);const result={D:0,R:0,I:0};r.candidates.forEach((c,i)=>{result[c.party]+=weights[i]/sum;});return result;}}const entry=r[mode];if(entry.rating==='tossup')return {D:.5,R:.5,I:0};const chance=s.ratingChances[entry.rating]/100;const result={D:0,R:0,I:0};result[entry.party]=chance;const opponents=(['D','R'] as Party[]).filter(x=>x!==entry.party);for(const party of opponents)result[party]=(1-chance)/opponents.length;return result;}
export function forecast(s:Senate,mode:Mode){const baseD=s.baseline.D+(s.baseline.independentCaucus==='D'?s.baseline.I:0);const baseR=s.baseline.R+(s.baseline.independentCaucus==='R'?s.baseline.I:0);let dist=new Map<string,number>([[`${baseD},${baseR}`,1]]);for(const race of s.races){const p=raceProbabilities(race,mode,s);const next=new Map<string,number>();for(const [key,chance] of dist){const [d,r]=key.split(',').map(Number);for(const party of ['D','R','I'] as Party[]){const caucus=party==='I'?race.independentCaucus:party;const k=`${d+(caucus==='D'?1:0)},${r+(caucus==='R'?1:0)}`;next.set(k,(next.get(k)||0)+chance*p[party]);}}dist=next;}let D=0,R=0,other=0,expectedD=0,expectedR=0;for(const [key,p]of dist){const [d,r]=key.split(',').map(Number);expectedD+=d*p;expectedR+=r*p;if(d>=51||(d===50&&s.tieBreaker==='D'))D+=p;else if(r>=51||(r===50&&s.tieBreaker==='R'))R+=p;else other+=p;}return {D,R,other,expectedD,expectedR};}
export function validateSenate(v:any):asserts v is Senate{const fail=()=>{throw Error('Check the Senate fields, seat total, and probability totals.');};const party=(x:any)=>['D','R','I'].includes(x);const num=(x:any,min:number,max:number,integer=false)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max&&(!integer||Number.isSafeInteger(x));const str=(x:any,n=1000)=>typeof x==='string'&&x.length<=n;if(!v||v.id!=='senate-2026'||!str(v.title,200)||!v.title.trim()||!str(v.updated,100)||!v.baseline||!party(v.tieBreaker)||!party(v.baseline.independentCaucus)||!v.ratingChances||!v.uncertainty||!Array.isArray(v.races)||v.races.length!==35)fail();for(const p of ['D','R','I'])if(!num(v.baseline[p],0,100,true))fail();if(v.baseline.D+v.baseline.R+v.baseline.I+v.races.length!==100)fail();for(const rating of ['safe','likely','lean'])if(!num(v.ratingChances[rating],50,100))fail();if(v.ratingChances.safe<v.ratingChances.likely||v.ratingChances.likely<v.ratingChances.lean)fail();for(const mode of ['polling','results'])if(!num(v.uncertainty[mode],.1,100))fail();const ids=new Set();for(const r of v.races){if(!r||!str(r.id,10)||!names[r.code]||r.id!==r.code||ids.has(r.id)||!str(r.state,100)||!party(r.incumbent)||!party(r.independentCaucus)||!str(r.incumbentName,200)||!str(r.notes,10000)||!str(r.source,2000)||!Array.isArray(r.candidates)||r.candidates.length<1||r.candidates.length>20)fail();ids.add(r.id);const cids=new Set();for(const c of r.candidates){if(!str(c.id,100)||!c.id||cids.has(c.id)||!str(c.name,200)||!party(c.party)||!num(c.poll,0,100)||!num(c.votes,0,1e9,true))fail();cids.add(c.id);}if(r.candidates.reduce((n:number,c:any)=>n+c.poll,0)>100.001)fail();for(const mode of ['polling','results']){const x=r[mode],p=r.probabilities?.[mode];if(!x||!party(x.party)||!['safe','likely','lean','tossup'].includes(x.rating)||!p||typeof p.manual!=='boolean'||typeof p.useNumbers!=='boolean')fail();for(const party of ['D','R','I'])if(!num(p[party],0,100))fail();if(p.manual&&Math.abs(p.D+p.R+p.I-100)>.001)fail();}if(!num(r.results.reporting,0,100)||!str(r.results.called,100)||(r.results.called&&!cids.has(r.results.called)))fail();}if(ids.size!==35)fail();}
