import {useEffect,useState} from 'react';
import {AppLink} from '../../../src/navigation';
import {saveContent} from '../../../lib/editor-api';
import {deliveryMode,publicationLabel,scheduledInstant,type Delivery} from '../../../lib/publication';
import {educationCategories,educationCategory,newEducational,educationalRoute,type Educational} from '../../../lib/education.mjs';
import {PublicationFields} from '../publication-fields';
import {EducationalArticle} from '../../education/article';
type Draft=Educational&{scheduleLocal?:string};
export default function Workspace({initial}:{initial:Educational[]}){
 const [items,setItems]=useState(initial),[selected,setSelected]=useState<Draft|undefined>(()=>{const first=initial.find(a=>!a.archived);return first?structuredClone(first):undefined;});
 const [delivery,setDelivery]=useState<Delivery>(()=>selected?deliveryMode(selected):'draft');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const listed=items.filter(a=>!a.archived&&(!filter||a.educationCategory===filter)&&[a.title,a.summary,educationCategory(a.educationCategory)?.name].join(' ').toLowerCase().includes(query.toLowerCase()));
 const trash=items.filter(a=>a.archived);
 const canLeave=()=>!dirty||confirm('Discard unsaved changes to this educational?');
 function choose(article?:Educational){if(busy||!canLeave())return;setSelected(article?structuredClone(article):newEducational());setDelivery(article?deliveryMode(article):'draft');setPreview(false);setDirty(false);setMessage('');}
 function update<K extends keyof Draft>(key:K,value:Draft[K]){setSelected(a=>a?{...a,[key]:value}:a);setDirty(true);setMessage('Unsaved changes');}
 const upsert=(article:Educational)=>setItems(old=>old.some(a=>a.id===article.id)?old.map(a=>a.id===article.id?article:a):[article,...old]);
 async function save(){if(busy||!selected)return;setBusy(true);setMessage('Saving…');try{
  const {scheduleLocal,...fields}=selected;let publishAt='';if(delivery==='scheduled'){publishAt=scheduleLocal!==undefined?scheduledInstant(scheduleLocal):fields.publishAt||'';if(!publishAt)throw Error('Choose a publication date and time.');if(Date.parse(publishAt)<=Date.now()&&publishAt!==items.find(a=>a.id===fields.id)?.publishAt)throw Error('Choose a future publication time.');}
  const value:Educational={...fields,category:educationCategory(fields.educationCategory)!.name,status:delivery==='draft'?'draft':'published',publishAt};
  await saveContent('article',value);upsert(value);setSelected(structuredClone(value));setDirty(false);setMessage(publicationLabel(value)==='Scheduled'?'Educational scheduled.':value.status==='published'?'Educational saved and published.':'Draft saved.');
 }catch(e:any){setMessage(e.message||'Save failed. Your changes are still in the form.');}finally{setBusy(false);}}
 async function remove(){if(!selected||busy)return;const saved=items.find(a=>a.id===selected.id);if(!confirm(saved?`Move “${saved.title}” to trash and unpublish it? You can restore it as a draft.`:'Discard this unsaved educational?'))return;if(!saved){setSelected(undefined);setDirty(false);setMessage('Unsaved educational discarded.');return;}setBusy(true);try{const removed:Educational={...saved,status:'draft',publishAt:'',archived:true};await saveContent('article',removed);upsert(removed);setSelected(undefined);setDirty(false);setPreview(false);setMessage('Moved to trash and unpublished.');}catch(e:any){setMessage(e.message||'Could not remove this educational.');}finally{setBusy(false);}}
 async function restore(article:Educational){if(busy||!canLeave())return;setBusy(true);try{const restored:Educational={...article,status:'draft',publishAt:'',archived:false};await saveContent('article',restored);upsert(restored);setSelected(structuredClone(restored));setDelivery('draft');setDirty(false);setPreview(false);setMessage('Restored as a private draft.');}catch(e:any){setMessage(e.message||'Could not restore this educational.');}finally{setBusy(false);}}
 function moveSection(index:number,direction:number){if(!selected)return;const sections=[...selected.sections],other=index+direction;[sections[index],sections[other]]=[sections[other],sections[index]];update('sections',sections);}
 return <main className="newsroom"><div className="sectionhead"><h1>Education newsroom</h1><AppLink action href="/editor">Private newsroom</AppLink><AppLink action href="/education" target="_blank">View Education</AppLink></div><p className="meta">Write our explainers, organize them by topic, and save drafts or publish when ready.</p>
  <div className="editorlayout"><aside className="editorlist"><button className="primary new" disabled={busy} onClick={()=>choose()}>+ New educational</button><label>Search educationals<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title or topic"/></label><label>Category<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All categories</option>{educationCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   {listed.map(a=><button disabled={busy} key={a.id} className={'record '+(selected?.id===a.id?'chosen':'')} onClick={()=>choose(a)}><b>{a.title}</b><span>{educationCategory(a.educationCategory)?.name} · {publicationLabel(a)}</span></button>)}{!listed.length&&<p className="meta">{items.some(a=>!a.archived)?'No educationals match these filters.':'Create our first educational to get started.'}</p>}
   <details className="newsroom-trash"><summary>Trash ({trash.length})</summary>{trash.map(a=><div key={a.id}><b>{a.title}</b><button disabled={busy} onClick={()=>restore(a)}>Restore as draft</button></div>)}</details>
  </aside><section className="editorform">{!selected?<p role="status">{message||'Select an educational or create a new one.'}</p>:<><div className="formhead"><h2>Educational editor</h2><button disabled={busy} onClick={remove}>Remove educational</button><button disabled={busy} onClick={()=>setPreview(!preview)}>{preview?'Edit':'Preview'}</button></div>
   {preview?<div className="draftpreview"><EducationalArticle article={selected} preview/></div>:<form aria-busy={busy} onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy} className="education-fields"><label>Title<input required maxLength={200} value={selected.title} onChange={e=>update('title',e.target.value)}/></label>
    <div className="fieldrow"><label>Category<select value={selected.educationCategory} onChange={e=>update('educationCategory',e.target.value as Educational['educationCategory'])}>{educationCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Author<input required maxLength={200} value={selected.author} onChange={e=>update('author',e.target.value)}/></label></div>
    <label>Summary<textarea rows={3} maxLength={2000} value={selected.summary} onChange={e=>update('summary',e.target.value)}/><small>A short introduction for readers and search results.</small></label>
    <label>Lesson text / introduction<textarea className="bodyfield" rows={12} maxLength={100000} value={selected.body} onChange={e=>update('body',e.target.value)}/><small>Separate paragraphs with a blank line. Add optional sections below for longer explainers.</small></label>
    <h3>Sections</h3>{selected.sections.map((section,i)=><fieldset key={section.id}><legend>Section {i+1}</legend><label>Heading<input required={delivery!=='draft'} maxLength={200} value={section.title} onChange={e=>update('sections',selected.sections.map(s=>s.id===section.id?{...s,title:e.target.value}:s))}/></label><label>Text<textarea required={delivery!=='draft'} rows={7} maxLength={30000} value={section.body} onChange={e=>update('sections',selected.sections.map(s=>s.id===section.id?{...s,body:e.target.value}:s))}/></label><div className="education-section-actions"><button type="button" disabled={i===0} onClick={()=>moveSection(i,-1)}>Move up</button><button type="button" disabled={i===selected.sections.length-1} onClick={()=>moveSection(i,1)}>Move down</button><button type="button" onClick={()=>update('sections',selected.sections.filter(s=>s.id!==section.id))}>Remove section</button></div></fieldset>)}<button type="button" disabled={selected.sections.length>=50} onClick={()=>update('sections',[...selected.sections,{id:crypto.randomUUID(),title:'',body:''}])}>+ Add section</button>
    <h3>Sources & further reading</h3>{selected.sources.map((source,i)=><fieldset key={i}><legend>Source {i+1}</legend><label>Name<input required maxLength={300} value={source.label} onChange={e=>update('sources',selected.sources.map((s,j)=>j===i?{...s,label:e.target.value}:s))}/></label><label>HTTPS URL<input required type="url" maxLength={2000} value={source.url} onChange={e=>update('sources',selected.sources.map((s,j)=>j===i?{...s,url:e.target.value}:s))}/></label><button type="button" onClick={()=>update('sources',selected.sources.filter((_,j)=>j!==i))}>Remove source</button></fieldset>)}<button type="button" disabled={selected.sources.length>=30} onClick={()=>update('sources',[...selected.sources,{label:'',url:''}])}>+ Add source</button>
    <PublicationFields article={selected} delivery={delivery} onDelivery={value=>{setDelivery(value);setDirty(true);setMessage('Unsaved changes');}} onTime={value=>update('scheduleLocal',value)} onDate={value=>update('date',value)}/>
    <div className="savebar"><button className="primary" disabled={busy}>{busy?'Saving…':delivery==='scheduled'?'Save schedule':delivery==='published'?'Save & publish':'Save draft'}</button><span role="status">{message}</span></div>
   </fieldset></form>}{preview&&<p role="status">{message}</p>}{selected.status==='published'&&!dirty&&publicationLabel(selected)==='Published'&&<p className="meta"><AppLink action href={educationalRoute(selected.id)} target="_blank">Open published educational</AppLink></p>}
  </>}</section></div>
 </main>;
}
