import { env } from 'cloudflare:workers';
export type Article = {id:string; title:string; category:string; summary:string; body:string; author:string; status:'draft'|'published'; date:string};
export type Election = {id:string; title:string; date:string; reporting:number; status:string; candidates:{name:string;party:string;votes:number;color:string}[]};
export const samples:Article[]=[{id:'a1',title:'A close race, a consequential choice',category:'ANALYSIS',summary:'As election day approaches, the contest turns to the issues shaping everyday life.',body:'The final weeks of the campaign have brought the debate back to familiar ground: public services, the cost of living, and trust in local government.\n\nFor voters, the choice is about priorities as much as personalities. Candidates have offered competing plans for transport, housing, and the next council budget.\n\nThis is fictional sample coverage. Replace this article in the private newsroom before publishing your own election reporting.',author:'Election Desk',status:'published',date:'2026-09-30'}, {id:'a2',title:'How to read the results on election night',category:'EXPLAINER',summary:'Reporting percentages, vote totals, and race calls explained.',body:'Early returns rarely tell the whole story. Different districts report at different times, and a lead can change as more ballots are counted.\n\nOur results show the share of precincts reporting alongside each candidate’s total. A race remains unofficial until the relevant authority certifies the result.\n\nThese are demonstration results, not a live election feed.',author:'Election Desk',status:'published',date:'2026-09-29'}, {id:'a3',title:'The issues behind the campaign',category:'POLITICS',summary:'Housing and transport lead the conversation in the fictional borough of Westbridge.',body:'In Westbridge, the campaign has centered on how a growing borough should invest in its future.\n\nCandidates disagree on the pace of new housing and the best way to connect residents to jobs and services. This fictional story is a starting point for your own coverage.',author:'Election Desk',status:'published',date:'2026-09-28'}];
export const sampleElection:Election={id:'e1',title:'Westbridge mayor',date:'2026-11-03',reporting:64,status:'Unofficial · sample results',candidates:[{name:'Alex Morgan',party:'Civic Alliance',votes:18420,color:'#245c91'},{name:'Jamie Reed',party:'Progress Party',votes:17380,color:'#be3835'},{name:'Sam Taylor',party:'Independent',votes:4200,color:'#b99338'}]};
function db(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
export async function content(all=false){const rows=await db().prepare('SELECT * FROM records ORDER BY updated DESC').all<any>(); const articles=rows.results.filter(r=>r.kind==='article').map(r=>JSON.parse(r.data));const elections=rows.results.filter(r=>r.kind==='election').map(r=>JSON.parse(r.data));return {articles:(articles.length?articles:samples).filter(a=>all||a.status==='published'),elections:elections.length?elections:[sampleElection]};}
export async function isEditor(id:string){return !!await db().prepare('SELECT id FROM editors WHERE id=?').bind(id).first();}
export async function claimEditor(id:string){await db().prepare('INSERT INTO editors(id) SELECT ? WHERE NOT EXISTS(SELECT 1 FROM editors)').bind(id).run();return isEditor(id);}
export async function save(kind:string,value:any){const now=new Date().toISOString();await db().prepare('INSERT INTO records(id,kind,data,updated) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(value.id,kind,JSON.stringify(value),now).run();}
export async function initialize(){const existing=await db().prepare('SELECT id FROM records LIMIT 1').first();if(!existing)await db().batch([...samples.map(a=>db().prepare('INSERT OR IGNORE INTO records(id,kind,data,updated) VALUES(?,?,?,?)').bind(a.id,'article',JSON.stringify(a),a.date)),db().prepare('INSERT OR IGNORE INTO records(id,kind,data,updated) VALUES(?,?,?,?)').bind(sampleElection.id,'election',JSON.stringify(sampleElection),new Date().toISOString())]);}
