import fs from 'node:fs';import ts from 'typescript';import assert from 'node:assert/strict';
function moduleUrl(file,imports={}){let source=fs.readFileSync(file,'utf8');for(const [from,to]of Object.entries(imports))source=source.replaceAll("'"+from+"'","'"+to+"'");const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return 'data:text/javascript;base64,'+Buffer.from(js).toString('base64');}
const worldURL=moduleUrl('lib/world.ts');const model=await import(worldURL);const {seedWorldElections}=await import(moduleUrl('lib/world-seeds.ts',{'./world':worldURL}));const {seedCountries}=await import(moduleUrl('lib/world-countries.ts',{'./world':worldURL}));
for(const country of seedCountries)model.validateCountry(country);assert.equal(new Set(seedCountries.map(c=>c.id)).size,seedCountries.length);assert.ok(seedCountries.length>=190);for(const election of seedWorldElections){model.validateWorldElection(election);assert.ok(seedCountries.some(c=>c.id===election.countryId));}assert.equal(new Set(seedWorldElections.map(e=>e.id)).size,seedWorldElections.length);
const draft={...seedWorldElections[0],publication:'draft'};assert.equal(model.publishedWorld({countries:seedCountries,elections:[draft]}).elections.length,0);
const multi={...seedWorldElections[0],startDate:'2026-10-30',endDate:'2026-11-03'};assert.deepEqual(model.calendarDays(multi,'2026-10'),['2026-10-30','2026-10-31']);assert.deepEqual(model.calendarDays(multi,'2026-11'),['2026-11-01','2026-11-02','2026-11-03']);assert.deepEqual(model.calendarDays({...multi,precision:'month'},'2026-10'),[]);assert.deepEqual(model.calendarDays({...multi,status:'postponed'},'2026-10'),[]);
assert.equal(model.validDate('2026-02-30'),false);assert.equal(model.validDate('2024-02-29'),true);assert.equal(model.dateLabel({...multi,startDate:'2027-04-18',endDate:'',precision:'month'}),'April 2027');assert.equal(model.dateLabel({...multi,startDate:'',endDate:'',precision:'unknown'}),'Date not announced');
assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],sources:[]}));assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],startDate:'2026-02-30'}));assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],sources:[{label:'Unsafe',url:'javascript:alert(1)'}]}));assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],sources:[{label:'Unsafe',url:'https://user:secret@example.org'}]}));assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],results:[{id:'x',name:'Bad',party:'',color:'#123456',votes:-1,share:null,seats:null,electoralVotes:null,winner:false}]}));
assert.ok(seedWorldElections.filter(e=>e.status==='held').some(e=>e.results.length));const fr=seedWorldElections.filter(e=>e.seriesId==='france-president-2027');assert.equal(fr.length,2);
const explore=await import(moduleUrl('lib/explore.ts',{'./world':worldURL}));const us=seedWorldElections.filter(e=>e.countryId==='us'&&e.status==='held');assert.equal(explore.comparable(us[0],us[1]),true);assert.equal(explore.comparable(us[0],{...us[1],body:'Senate'}),false);assert.equal(explore.metric(undefined,'seats'),null);const chamber={...seedWorldElections[0],totalSeats:122,majorityThreshold:null};assert.equal(explore.majority(chamber),62);assert.equal(explore.majority({...chamber,majorityThreshold:61}),61);assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],live:{enabled:true,reporting:101,unit:'precincts',bulletin:'',updated:''}}));assert.throws(()=>model.validateWorldElection({...seedWorldElections[0],totalSeats:100,majorityThreshold:101}));model.validateWorldElection({...seedWorldElections[0],live:{enabled:true,reporting:null,unit:'precincts',bulletin:'Waiting for figures',updated:''},coalitionNotes:'Editorial guidance',majorityThreshold:null});const geometry=JSON.parse(fs.readFileSync('lib/atlas-map.json','utf8'));assert.ok(geometry.length>190);for(const code of ['us','gb','nl','br','za','in'])assert.ok(geometry.some(x=>x.id===code&&x.path.startsWith('M')));
console.log(JSON.stringify({validated:true,countries:seedCountries.length,elections:seedWorldElections.length,calendar:seedWorldElections.filter(e=>e.status==='scheduled').length,archive:seedWorldElections.filter(e=>e.status==='held').length,resultTables:seedWorldElections.filter(e=>e.results.length).length,checks:['draft privacy','date precision','month-boundary voting periods','date validation','sources','safe URLs','result validation','linked rounds']}));
